# Generated by Django 2.2.5 on 2020-01-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='money',
            name='batch',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='money',
            name='roll',
            field=models.IntegerField(),
        ),
    ]
