# Generated by Django 2.2.5 on 2020-01-23 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='amount',
            new_name='register',
        ),
    ]
