# Generated by Django 2.2.5 on 2020-01-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_auto_20200123_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='register',
        ),
    ]
