# Generated by Django 2.2.5 on 2020-01-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_remove_students_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='batch',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='roll',
            field=models.IntegerField(),
        ),
    ]
